repos:
  - repo: local
    hooks:
      - id: mypy
        name: MyPy Type Check
        entry: mypy --ignore-missing-imports .
        language: system
        types: [python]
        pass_filenames: false
        files: \.py$

      - id: ruff-check
        name: Ruff Error Check
        entry: ruff check
        language: system
        types: [python]
        pass_filenames: false
        files: \.py$

      - id: ruff-format
        name: Ruff Code Formatting
        entry: ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
        files: \.py$
